//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetinCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TweetinCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Modified - There was no new data to return..
        /// </summary>
        internal static string ExceptionDescription_304 {
            get {
                return ResourceManager.GetString("ExceptionDescription_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response..
        /// </summary>
        internal static string ExceptionDescription_400 {
            get {
                return ResourceManager.GetString("ExceptionDescription_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized -  Authentication credentials were missing or incorrect..
        /// </summary>
        internal static string ExceptionDescription_401 {
            get {
                return ResourceManager.GetString("ExceptionDescription_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits..
        /// </summary>
        internal static string ExceptionDescription_403 {
            get {
                return ResourceManager.GetString("ExceptionDescription_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found - The URI requested is invalid or the resource requested, such as a user, does not exists. Also returned when the requested format is not supported by the requested method..
        /// </summary>
        internal static string ExceptionDescription_404 {
            get {
                return ResourceManager.GetString("ExceptionDescription_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Acceptable - Returned by the Search API when an invalid format is specified in the request..
        /// </summary>
        internal static string ExceptionDescription_406 {
            get {
                return ResourceManager.GetString("ExceptionDescription_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone - This resource is gone. Used to indicate that an API endpoint has been turned off. For example: &quot;The Twitter REST API v1 will soon stop functioning. Please migrate to API v1.1..
        /// </summary>
        internal static string ExceptionDescription_410 {
            get {
                return ResourceManager.GetString("ExceptionDescription_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessable Entity - Returned when an image uploaded to POST account/update_profile_banner is unable to be processed..
        /// </summary>
        internal static string ExceptionDescription_422 {
            get {
                return ResourceManager.GetString("ExceptionDescription_422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many Requests - Returned in API v1.1 when a request cannot be served due to the application&apos;s rate limit having been exhausted for the resource. See Rate Limiting in API v1.1..
        /// </summary>
        internal static string ExceptionDescription_429 {
            get {
                return ResourceManager.GetString("ExceptionDescription_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error - Something is broken. Please post to the group so the Twitter team can investigate..
        /// </summary>
        internal static string ExceptionDescription_500 {
            get {
                return ResourceManager.GetString("ExceptionDescription_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gateway - Twitter is down or being upgraded..
        /// </summary>
        internal static string ExceptionDescription_502 {
            get {
                return ResourceManager.GetString("ExceptionDescription_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable - The Twitter servers are up, but overloaded with requests. Try again later..
        /// </summary>
        internal static string ExceptionDescription_503 {
            get {
                return ResourceManager.GetString("ExceptionDescription_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway timeout - The Twitter servers are up, but the request couldn&apos;t be serviced due to some failure within our stack. Try again later..
        /// </summary>
        internal static string ExceptionDescription_504 {
            get {
                return ResourceManager.GetString("ExceptionDescription_504", resourceCulture);
            }
        }
    }
}
